language: node_js
node_js:
  - '0.12'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test-travis
  - npm run browser-test-travis
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
